---
abstract: 'simple job tank manager.'
author:
  - 'Atsushi Kobayashi <nekokak _at_ gmail _dot_ com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.94
  Test::mysqld: 0
  Test::postgresql: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jonk
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Try::Tiny: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/nekokak/p5-Jonk.git
version: 0.02
